main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('world/', views.world, name='world'),
  path('search/', views.search, name='search'),
  path('about/', views.about, name='about'),
  # Destinations
  path('destination/', views.dest_index, name='index'),
  path('destination/<int:dest_id>/', views.dest_detail, name='dest_detail'),
  path('destination/create/', views.DestCreate.as_view(), name='destination_create'),
  path('destination/<int:pk>/update/', views.DestUpdate.as_view(), name='dest_update'),
  path('destination/<int:pk>/delete/', views.DestDelete.as_view(), name='dest_delete'),
  # Activities\/\/
  path('activities/<int:dest_id>/create/', views.add_activity, name='act_create'),
  path('activities/<int:pk>/delete/', views.ActDelete.as_view(), name='act_delete'),
  path('activities/<int:pk>/update/', views.ActUpdate.as_view(), name='act_update'),
  # Posts\/\/
  path('posts/', views.post_index, name='post_index'),
  path('posts/<int:post_id>/detail', views.post_detail, name='post_detail'),
  path('posts/create/', views.PostCreate.as_view(), name='post_create'),
  path('posts/<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
  path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
  # Photos
  path('photos/<int:post_id>/add_photo', views.add_photo, name='add_photo'),
  path('photos/<int:pk>/update/', views.PostActUpdate.as_view(), name='post_act_update'),
  path('photos/<int:pk>/delete/', views.PostActDelete.as_view(), name='post_act_delete'),
  # Users
  path('accounts/signup/', views.signup, name='signup'),

    
  # path('destinations/<int:pk>/update/', views.DestinationsUpdate.as_view(), name='destinations_update'),
  # path('destinations/<int:pk>/delete/', views.DestinationsDelete.as_view(), name='destinations_delete'),
  # path('destinations/<int:destinations_id>/add_accomodation/', views.add_accomodation, name='add_accomodation'),
  # path('destinations/<int:destinations_id>/add_photo/', views.add_photo, name='add_photo'),
  # path('destinations/<int:destinations_id>/assoc_activities/<int:activities_id>/', views.assoc_activities, name='assoc_activities'),
  # path('destinations/<int:destinations_id>/unassoc_activities/<int:activities_id>/', views.unassoc_activities, name='unassoc_activities'),
  # path('activities/', views.ActivitiesList.as_view(), name='activities_index'),
  # path('activities/<int:pk>/', views.ActivitiesDetail.as_view(), name='activities_detail'),
  
]

tripplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('main_app.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date 
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.


class Destination(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField('Trip Date',default='')
    days = models.IntegerField(default=1)
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    notes = models.TextField(max_length=250, default='')

    def get_absolute_url(self):
        return reverse('dest_detail', kwargs={'dest_id': self.id})

class Activities(models.Model):
    name = models.CharField(max_length=50)
    destination = models.ForeignKey(Destination,on_delete=models.CASCADE)
    duration = models.IntegerField(null=False, blank=False)
    date = models.DateField('Activity date',default=date.today)
    notes = models.TextField(max_length=250,default='')

    def get_absolute_url(self):
        return reverse('index')

RATING= (('1', '*'),('2','* *' ),('3', '* * *'),('4', '* * * *'),('5', '* * * * *'))


class Posts(models.Model):
    user= models.ForeignKey(User, on_delete=models.CASCADE)
    date = date.today
    description=models.CharField(max_length=50,default='', null=False, blank=False)
    comment = models.TextField(max_length=250)
    rating = models.CharField(
        max_length=1,
        choices = RATING,
        default=RATING[0][0])

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'post_id': self.id})


class Photo(models.Model):
    url = models.CharField(max_length=200)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, default='',blank=True)
    comment = models.TextField(max_length=250, default="No comment")
    time = models.TimeField(auto_now=False, auto_now_add=False, default=timezone.now().time())

    def get_absolute_url(self):
        return reverse('post_index')
    
    class Meta:
        ordering = ['-time']

main_app/forms.py
from django.forms import ModelForm
from .models import Activities

class ActivitiesForm(ModelForm):
  class Meta:
    model = Activities
    fields = ['name', 'duration', 'date','notes']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import *
from django.db.models import Q
from .forms import ActivitiesForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# \/\/this is for the functions so it requires you to be logged in
from django.contrib.auth.decorators import login_required
#\/\/ this is for the BCV so it requires you to be logged in
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
import os

# Create your views here.
def home(request):
  return render(request, 'home.html')

def world(request):
  act = Photo.objects.all()
  for photo in act:
        print("photos obj: ",photo.url)
  
  return render(request, 'world.html', {'act':act})

def search(request):
  query = request.GET.get('q', '')
  act = Photo.objects.filter(Q(title__icontains=query))
  return render(request, 'world.html', {'act':act})


def about(request):
  return render(request, 'about.html')

@login_required
def dest_index(request):
  dest = Destination.objects.filter(user=request.user)
  return render(request, 'destinations/index.html', {
    'dest': dest
  })

# Destinations Functions\/\/\/

class DestCreate(LoginRequiredMixin,CreateView):
  model = Destination
  fields = ['name', 'date', 'days', 'notes']

  def form_valid(self,form):
    # form.instance: is the user object based on the user model we're enheriting
    form.instance.user = self.request.user
    return super().form_valid(form)

@login_required  
def dest_detail(request, dest_id):
    dest = Destination.objects.get(id=dest_id)
    act_form = ActivitiesForm()
    return render(request, 'destinations/detail.html', {
      'dest': dest, 'act_form': act_form
  })
  
class DestUpdate(LoginRequiredMixin,UpdateView):
  model = Destination
  fields = ['name', 'date', 'days', 'notes']

class DestDelete(LoginRequiredMixin,DeleteView):
  model = Destination
  success_url = '/destination'

# Activities Form\/\/\/

@login_required
def add_activity(request, dest_id):
  form = ActivitiesForm(request.POST)

  if form.is_valid():
    new_act = form.save(commit=False)
    new_act.destination_id = dest_id
    new_act.save()
    return redirect('dest_detail', dest_id=dest_id)

class ActUpdate(LoginRequiredMixin,UpdateView):
    model=Activities
    fields=['name','duration', 'date', 'notes']

class ActDelete(LoginRequiredMixin,DeleteView):
    model=Activities
    success_url='/destination'

    # Post Functions


def post_index(request):
  post = Posts.objects.filter(user=request.user)
  return render(request, 'post/index.html', {
    'post': post
  })

@login_required
def post_detail(request, post_id):
    post = Posts.objects.get(id=post_id)
    user_id=request.user.id
    return render(request, 'post/detail.html', {
      'post': post,"user":user_id
  })

class PostCreate(LoginRequiredMixin,CreateView):
    model = Posts
    fields = ['description','rating', 'comment']

    def form_valid(self,form):
      # form.instance: is the user object based on the user model we're enheriting
      form.instance.user = self.request.user
      return super().form_valid(form)
      
class PostUpdate(LoginRequiredMixin,UpdateView):
    model=Posts
    fields=['description','comment', 'rating']

class PostDelete(LoginRequiredMixin,DeleteView):
    model=Posts
    success_url='/posts'

# Posts Photos \/\/

# For debugging purposes\/\/
# credentials = boto3.Session().get_credentials()
# print("printing creds ")
# print("AWS Access Key:", credentials.access_key)
# print("AWS Secret Key:", credentials.secret_key)

@login_required
def add_photo(req, post_id):
    photo_file = req.FILES.get('photo-file', None)
    
    if photo_file:
        # Initialize the S3 client
        s3 = boto3.client('s3')
        # Generate a unique key for the file using uuid (6 characters) this: photo_file.name[photo_file.name.rfind('.'):] is getting the "." and the extention
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        
        try:
            # Get the bucket name and base URL from environment variables
            bucket = os.getenv('S3_BUCKET')
            file_extension = photo_file.name.split('.')[-1].lower()
            if file_extension == 'jpeg' or file_extension == 'jpg':
                content_type = 'image/jpeg'
            elif file_extension == 'png':
                content_type = 'image/png'
            elif file_extension == 'gif':
                content_type = 'image/gif'
            else:
                content_type = 'application/octet-stream'
            s3.upload_fileobj(photo_file, bucket, key, ExtraArgs={'ContentType': content_type})
            
            # Construct the image URL using the base URL
            url = f"{os.getenv('S3_BASE_URL')}/{key}"
            # Get the additional fields (comment, title) from the form
            comment = req.POST.get('comment', '')
            title = req.POST.get('title', '')
            
            # Save the image details to the database
            Photo.objects.create(url=url, post_id=post_id, comment=comment, title=title)
        except Exception as e:
            # Handle any errors during upload
            print('An error occurred uploading file to S3')
            print(e)
    
    return redirect('post_detail', post_id=post_id)

class PostActUpdate(LoginRequiredMixin,UpdateView):
    model=Photo
    fields=['title','comment']

class PostActDelete(LoginRequiredMixin,DeleteView):
    model=Photo
    success_url='/posts'

  # User Functions \/\/

def signup(req):
  error_message = ''
  if req.method == "POST":
    form = UserCreationForm(req.POST)
    if form.is_valid():
      user=form.save()
      login(req, user)
      return redirect('home')
    else:
      error_message = 'invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(req, 'registration/signup.html', context)

main_app/templates/destinations/detail.html
{% extends 'base.html' %}
{% block content %}


<div class="row">
  <div class="col-sm-s12">
    <h1 class="center display-1">{{ dest.name }}</h1>

<div class="container parallax-trips-edit">

<div class="row">
  <div class="col s6">
    <div class="card my-trip-notes" id="trips-cards" style="height: 13rem;">
      <div class="card-content" style="font-size: 1.1rem;">
        <h3 id="card-title">Notes for "{{ dest.name }}"</h3>
        <p>Date: {{ dest.date }}</p>
        <p>Days: {{ dest.days }}</p>
        <p>Notes: {{ dest.notes }}</p>
         
      
       <div class="d-grid gap-2 d-md-flex justify-content-md-center">
         <button type="submit" class="btn me-md-2"><a href="{% url 'dest_update' dest.id %}" id="add-trip-notes">Add To Trip Notes</a>
          </div>

         <form action="{% url 'dest_delete' dest.id %}" method="POST"></button>
          {% csrf_token %}
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <button type="submit" class="btn me-md-2 btn-remove-trip" style="font-family:Bebas Neue; font-size: 18px">Remove Trip</button>
          </div>
         </form>
       </div>
      </div>
  </div>
  {% for act in post.photo_set.all %}
  <div class="col s6">
<!-- form for adding activities -->
    <div id="show" style="cursor:pointer; font-size:22px;"><span style="font-size: 1.5em;">&#10753;</span>New Activity</div>
    
    <div class="d-grid gap-2 d-md-flex justify-content-md-center">
     <div class="menu" style="display: none;">
      <div class="card">
  {% endfor %}
        <!-- <div class="card-content">
            <span class="card-title center">Activity</span>
           <table class="table table-striped">
      
         <hr>
           <tbody>
            {% for act in dest.activities_set.all %}
             <tr>
              <td>{{act.name}}</td>
              <td>{{act.date}}</td>
              <td>{{act.duration}}</td>
              <td>{{act.notes}}</td> -->

              <!-- <td><a href="{% url 'act_update' act.id %}" class="btn blue darken-4">Update</a></td>
              <td> <form action="{% url 'act_delete' act.id  %}" method="POST">{% csrf_token %} <button type="submit" class="btn blue darken-4" style="font-family: Bebas Neue">REMOVE</button></form></td>
             </tr>
            {% endfor %}
           </tbody>
          </table>
          <br> -->
          <div class="d-grid gap-2 d-md-flex justify-content-md-center rounded" id="new-act-form">
          <form action="{% url 'act_create' dest.id %}" method="POST" class="mx-auto">
          {% csrf_token %} {{ act_form.as_p }}
          <input type="submit" class="btn blue accent-2" value="Add Activity" style="font-family: Bebas Neue">
          </div>
          </form>
          </div>
         </div>
        </div>
      </div>
    </div>
</div>
<table class="table table-striped table-hover table-dark">
  <thead>
    <tr id="trip-detail-table">
      <td id="trip-detail-table">Activity</td>
      <td>Date</td>
      <td>Hours</td>
      <td>Field Notes</td>
    </tr>
  </thead>
  <tbody>
    {% for act in dest.activities_set.all %}
    <tr>
      <td>{{ act.name}}</td>
      <td>{{ act.date}}</td>
      <td>{{ act.duration}}</td>
      <br>
      <td>{{ act.notes}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>
</div>


    <script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true
      });
  

    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
    $('#show').click(function() {
      $('.menu').toggle("slide");
    });
    });
    </script>

    <script>

    document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('.collapsible');
        var instances = M.Collapsible.init(elems, options);
    });

    

    </script>
    {% endblock %}

main_app/templates/destinations/index.html
{% extends 'base.html' %}
{% block content %}


<h1 class="display-1">Trips</h1>
<div class="container parallax">

<div class="row">
  {% for dest in dest %} 
  <div class="col-md center">
  <a href="{% url 'dest_detail' dest.id %}" class="trips-card-font zoom-on-hover" id="view-trip-form">
    <div class="card card-img-top" style="height: 13rem; width: 20rem;" id="trips-cards">
      <div class="card-content">
        <h4 id="card-title" class="d-flex justify-content-center">{{ dest.name }}</h4>
        <hr style="width: 80%;" class="mx-auto" id="trips-cards-line">
        <p><span>Date</span>:    {{ dest.date }}</p>
        <p><span>Days</span>:    {{ dest.days }}</p>
        <p><span>User</span>:   {{ dest.user.username }}</p>
        <p><span>Notes</span>:   {{ dest.notes }}</p>
        </div>
    </div>
  </a>
</div>
{% if forloop.counter|divisibleby:3 and not forloop.last %}
      </div><div class="row">
    {% endif %}
{% endfor %}
</div>


{% endblock %}